image: node:latest

cache:
  paths:
    - node_modules/
    - app/bower_components

deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - sudo npm install -g firebase-tools
    - sudo npm install -g bower
    - sudo npm install
    - sudo bower install --allow-root
    - sudo firebase use --token $FIREBASE_DEPLOY_KEY mytestproject-a1d69
    - sudo firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY




