image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "25"
  ANDROID_BUILD_TOOLS: "24.0.0"
  ANDROID_SDK_TOOLS: "24.4.1"

before_script:
  - echo $ANDROID_HOME

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew assembleDebug
    - ./gradlew assembleDebugAndroidTest

testFirebase:
  stage: test
  script:
    - gcloud firebase test android run firebase-test-matrix.yml:nexus5-device --type instrumentation --app app/build/outputs/apk/app-debug.apk --test app/build/outputs/apk/app-debug-androidTest.apk --project mytestproject-a1d69


